name: hand_landmarker_example
description: "Demonstrates how to use the hand_landmarker plugin."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  hand_landmarker: ^2.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  logging: ^1.0.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/new_icon.png
  branding_mode: bottom
  android: true
  ios: false
  web: false

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/mj2.webp
    - assets/images/logo.png